"""Embodiment / Actuation World Model — Phase 3.

Additive canonical state, receipts, shadow compiler, provider contracts, and
shadow downstream consumers for body/action/runtime-adjacent truth. This package
is advisory by default and does not modify frozen Phase B baseline math.
"""

from .compiler import (
    EmbodimentActuationCompilationInputs,
    EmbodimentActuationCompilationResult,
    compile_embodiment_actuation_with_receipts,
    compile_embodiment_actuation_world_state,
)
from .consumers import (
    EconomicEmbodimentReceiptBundle,
    PerceptionEmbodimentFeedbackSurface,
    RuntimeAdapterValidationContext,
    SimEmbodimentTransferContext,
    build_economic_embodiment_receipt_bundle,
    build_perception_embodiment_feedback,
    build_runtime_adapter_validation_context,
    build_sim_embodiment_transfer_context,
)
from .morphology import (
    G1MorphologyProfile,
    MorphologyEvidenceReceipt,
    MorphologyJointSpec,
    build_g1_morphology_profile,
    scan_unitree_g1_public_evidence,
)
from .neural_seams import (
    ActionProposalSeam,
    DriftCalibrationSeam,
    InverseRetargetingSeam,
    LocalContactDynamicsSeam,
    SeamForwardResult,
    encode_state_features,
    smoke_forward_all_seams,
)
from .neural_architectures import (
    ActionChunkingTransformerHead,
    DiffusionActionDenoiserHead,
    EmbodimentNeuralArchitectureManifest,
    EmbodimentNeuralArchitectureSpec,
    EmbodimentTopologyContrastiveHead,
    NEURAL_ARCHITECTURE_MANIFEST_VERSION,
    TemporalJEPALatentPredictor,
    build_embodiment_neural_architecture_manifest,
    build_embodiment_neural_architecture_specs,
    smoke_forward_neural_architectures,
)
from .promotion import EmbodimentSeamResolution, resolve_embodiment_seam
from .provider_contracts import (
    EmbodimentProviderContract,
    EmbodimentRuntimeResourceSurface,
    holosoma_contract,
    isaac_contract,
    unitree_g1_contract,
)
from .sidecars import (
    EmbodimentActuationSidecarBundle,
    EmbodimentActuationSidecarWriteResult,
    build_embodiment_actuation_sidecar_bundle,
    write_embodiment_actuation_sidecars,
)
from .training_corpus import (
    EmbodimentSeamTrainingRow,
    EmbodimentTrainingManifest,
    build_phase34_training_manifest,
    build_phase34_training_rows_from_state,
    load_phase34_training_rows_jsonl,
    write_phase34_training_rows_jsonl,
)
from .receipts import (
    ActionProposalReceipt,
    ActionSpaceValidationReceipt,
    CalibrationTargetReceipt,
    CapabilityProfileReceipt,
    ContactAffordanceReceipt,
    EmbodimentCompilationReceipt,
    EmbodimentCostReceipt,
    EmbodimentDriftReceipt,
    EmbodimentReceipt,
    InverseRetargetReceipt,
    LocalDynamicsReceipt,
    ObservationInterfaceReceipt,
    SafetyEnvelopeReceipt,
    SimEmbodimentTransferReceipt,
)
from .state import (
    EMBODIMENT_ACTUATION_WORLD_STATE_VERSION,
    ActionProposalBundleState,
    ActionSpaceState,
    ActuatorConfigurationState,
    CalibrationTargetState,
    CapabilityState,
    ContactAffordanceGraphState,
    ContactStateVector,
    EmbodimentActuationWorldState,
    EmbodimentCostVectorState,
    EmbodimentDriftSummaryState,
    EmbodimentProfileState,
    InverseRetargetTraceState,
    JointStateVector,
    LocalDynamicsForecastState,
    ObservationInterfaceState,
    SafetyEnvelopeState,
)

__all__ = [
    "ActionProposalSeam",
    "ActionChunkingTransformerHead",
    "DiffusionActionDenoiserHead",
    "DriftCalibrationSeam",
    "EmbodimentNeuralArchitectureManifest",
    "EmbodimentNeuralArchitectureSpec",
    "EmbodimentSeamTrainingRow",
    "EmbodimentTrainingManifest",
    "EmbodimentTopologyContrastiveHead",
    "G1MorphologyProfile",
    "InverseRetargetingSeam",
    "LocalContactDynamicsSeam",
    "MorphologyEvidenceReceipt",
    "MorphologyJointSpec",
    "SeamForwardResult",
    "TemporalJEPALatentPredictor",
    "NEURAL_ARCHITECTURE_MANIFEST_VERSION",
    "build_g1_morphology_profile",
    "build_embodiment_neural_architecture_manifest",
    "build_embodiment_neural_architecture_specs",
    "build_phase34_training_manifest",
    "build_phase34_training_rows_from_state",
    "encode_state_features",
    "load_phase34_training_rows_jsonl",
    "scan_unitree_g1_public_evidence",
    "smoke_forward_all_seams",
    "smoke_forward_neural_architectures",
    "write_phase34_training_rows_jsonl",
    "EMBODIMENT_ACTUATION_WORLD_STATE_VERSION",
    "ActionProposalBundleState",
    "ActionProposalReceipt",
    "ActionSpaceState",
    "ActionSpaceValidationReceipt",
    "ActuatorConfigurationState",
    "CalibrationTargetReceipt",
    "CalibrationTargetState",
    "CapabilityProfileReceipt",
    "CapabilityState",
    "ContactAffordanceGraphState",
    "ContactAffordanceReceipt",
    "ContactStateVector",
    "EconomicEmbodimentReceiptBundle",
    "EmbodimentActuationCompilationInputs",
    "EmbodimentActuationCompilationResult",
    "EmbodimentActuationSidecarBundle",
    "EmbodimentActuationSidecarWriteResult",
    "EmbodimentActuationWorldState",
    "EmbodimentCompilationReceipt",
    "EmbodimentCostReceipt",
    "EmbodimentCostVectorState",
    "EmbodimentDriftReceipt",
    "EmbodimentDriftSummaryState",
    "EmbodimentProfileState",
    "EmbodimentProviderContract",
    "EmbodimentReceipt",
    "EmbodimentRuntimeResourceSurface",
    "EmbodimentSeamResolution",
    "InverseRetargetReceipt",
    "InverseRetargetTraceState",
    "JointStateVector",
    "LocalDynamicsForecastState",
    "LocalDynamicsReceipt",
    "ObservationInterfaceReceipt",
    "ObservationInterfaceState",
    "PerceptionEmbodimentFeedbackSurface",
    "RuntimeAdapterValidationContext",
    "SafetyEnvelopeReceipt",
    "SafetyEnvelopeState",
    "SimEmbodimentTransferContext",
    "SimEmbodimentTransferReceipt",
    "build_economic_embodiment_receipt_bundle",
    "build_embodiment_actuation_sidecar_bundle",
    "build_perception_embodiment_feedback",
    "build_runtime_adapter_validation_context",
    "build_sim_embodiment_transfer_context",
    "compile_embodiment_actuation_with_receipts",
    "compile_embodiment_actuation_world_state",
    "holosoma_contract",
    "isaac_contract",
    "resolve_embodiment_seam",
    "unitree_g1_contract",
    "write_embodiment_actuation_sidecars",
]
