"""Embodiment / Actuation World Model — Phase 3.

Additive canonical state, receipts, shadow compiler, provider contracts, and
shadow downstream consumers for body/action/runtime-adjacent truth. This package
is advisory by default and does not modify frozen Phase B baseline math.
"""

from .compiler import (
    EmbodimentActuationCompilationInputs,
    EmbodimentActuationCompilationResult,
    compile_embodiment_actuation_with_receipts,
    compile_embodiment_actuation_world_state,
)
from .consumers import (
    EconomicEmbodimentReceiptBundle,
    PerceptionEmbodimentFeedbackSurface,
    RuntimeAdapterValidationContext,
    SimEmbodimentTransferContext,
    build_economic_embodiment_receipt_bundle,
    build_perception_embodiment_feedback,
    build_runtime_adapter_validation_context,
    build_sim_embodiment_transfer_context,
)
from .promotion import EmbodimentSeamResolution, resolve_embodiment_seam
from .provider_contracts import (
    EmbodimentProviderContract,
    EmbodimentRuntimeResourceSurface,
    holosoma_contract,
    isaac_contract,
    unitree_g1_contract,
)
from .receipts import (
    ActionProposalReceipt,
    ActionSpaceValidationReceipt,
    CalibrationTargetReceipt,
    CapabilityProfileReceipt,
    ContactAffordanceReceipt,
    EmbodimentCompilationReceipt,
    EmbodimentCostReceipt,
    EmbodimentDriftReceipt,
    EmbodimentReceipt,
    InverseRetargetReceipt,
    LocalDynamicsReceipt,
    ObservationInterfaceReceipt,
    SafetyEnvelopeReceipt,
    SimEmbodimentTransferReceipt,
)
from .state import (
    EMBODIMENT_ACTUATION_WORLD_STATE_VERSION,
    ActionProposalBundleState,
    ActionSpaceState,
    ActuatorConfigurationState,
    CalibrationTargetState,
    CapabilityState,
    ContactAffordanceGraphState,
    ContactStateVector,
    EmbodimentActuationWorldState,
    EmbodimentCostVectorState,
    EmbodimentDriftSummaryState,
    EmbodimentProfileState,
    InverseRetargetTraceState,
    JointStateVector,
    LocalDynamicsForecastState,
    ObservationInterfaceState,
    SafetyEnvelopeState,
)

__all__ = [
    "EMBODIMENT_ACTUATION_WORLD_STATE_VERSION",
    "ActionProposalBundleState",
    "ActionProposalReceipt",
    "ActionSpaceState",
    "ActionSpaceValidationReceipt",
    "ActuatorConfigurationState",
    "CalibrationTargetReceipt",
    "CalibrationTargetState",
    "CapabilityProfileReceipt",
    "CapabilityState",
    "ContactAffordanceGraphState",
    "ContactAffordanceReceipt",
    "ContactStateVector",
    "EconomicEmbodimentReceiptBundle",
    "EmbodimentActuationCompilationInputs",
    "EmbodimentActuationCompilationResult",
    "EmbodimentActuationWorldState",
    "EmbodimentCompilationReceipt",
    "EmbodimentCostReceipt",
    "EmbodimentCostVectorState",
    "EmbodimentDriftReceipt",
    "EmbodimentDriftSummaryState",
    "EmbodimentProfileState",
    "EmbodimentProviderContract",
    "EmbodimentReceipt",
    "EmbodimentRuntimeResourceSurface",
    "EmbodimentSeamResolution",
    "InverseRetargetReceipt",
    "InverseRetargetTraceState",
    "JointStateVector",
    "LocalDynamicsForecastState",
    "LocalDynamicsReceipt",
    "ObservationInterfaceReceipt",
    "ObservationInterfaceState",
    "PerceptionEmbodimentFeedbackSurface",
    "RuntimeAdapterValidationContext",
    "SafetyEnvelopeReceipt",
    "SafetyEnvelopeState",
    "SimEmbodimentTransferContext",
    "SimEmbodimentTransferReceipt",
    "build_economic_embodiment_receipt_bundle",
    "build_perception_embodiment_feedback",
    "build_runtime_adapter_validation_context",
    "build_sim_embodiment_transfer_context",
    "compile_embodiment_actuation_with_receipts",
    "compile_embodiment_actuation_world_state",
    "holosoma_contract",
    "isaac_contract",
    "resolve_embodiment_seam",
    "unitree_g1_contract",
]
